create jira ticket
parodos-dev/parodos pull request #189
Opened 2023-03-30 21:42 UTC by RichardW98

2023-04-01 16:00 UTC, anludke requested changes

2023-04-03 13:31 UTC, RichardW98 commented on workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/checker/JiraTicketApprovalWorkFlowCheckerTask.java
> +			if (result.getStatusCode().is2xxSuccessful() && result.getBody() != null) {
![Screenshot 2023-04-03 at 9 31 18 AM](https://user-images.githubusercontent.com/58698556/229524780-1457f674-c851-48c6-a910-30d211fc3e0b.png)

2023-04-03 13:32 UTC, RichardW98 commented on workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketCreationWorkFlowTask.java
> +			if (response.getStatusCode().is2xxSuccessful()) {
same reason as above

2023-04-04 13:49 UTC, anludke approved these changes

2023-04-04 13:49 UTC, merged